### ISSUE TITLE
LSP on MacOS

### ISSUE THREAD

**Issue by aliusmiles** [mauve/vscode-terraform#253] opened 2019-12-02 10:50 UTC
Anybody got LSP properly working on MacOS? Autocompletion just doesn't work for me at all, language server seeps to be simply exiting without no errors.

**Comment by beerygaz** [comment] 2019-12-12 12:13
Same issue here, but on MacOS and on Windows.

**Comment by oswalya** [comment] 2019-12-16 09:45
I have the same issue on MacOS

**Comment by rowleyaj** [comment] 2019-12-19 14:14
This might be a dupe of #232 ?

**Comment by beerygaz** [comment] 2019-12-20 05:13
The look related - certainly for me the behavior is the same across Windows and MacOS using the LSP

**Comment by stuzlogle** [comment] 2020-01-03 17:25
I have other issues but autocompletion works. I made the following change to my settings.json based on some conversation in another ticket:

```
    "terraform.languageServer": {
        "enabled": true,
        "args": [],
        "pathToBinary": "/Users/myuser/.vscode/extensions/mauve.terraform-1.4.0/lspbin"
    },
```

Also make sure terraform.indexing is disabled.

**Comment by aliusmiles** [comment] 2020-01-03 18:39
@stuzlogle many thanks! autocompletion now works for me after setting pathToBinary, both for resource's arguments and for resources themselves, although those works only without quotes:

```
resource aws_iam_user "test" {
  name = "test"
}
```
weird that terraform validate/plan is not complaining on that at all, but all the examples have resource's type in quotes. 


Final working config looks like following now:

```
{
    "terraform.path": "/Users/user/bin/terraform12",
    "terraform.indexing": {
        "enabled": false
    },
    "terraform.languageServer": {
        "enabled": true,
        "pathToBinary": "/Users/user/.vscode/extensions/mauve.terraform-1.4.0/lspbin",
        "args": []
    },
    "editor.formatOnSave": true
}
```
So that leaves only features not implemented in lsp yet, like tfvars and each, and chain restarts of lang server https://github.com/juliosueiras/terraform-lsp/issues/47 I guess. @stuzlogle would you mind to share your list of remaining issues with lsp on MacOS?

**Comment by stuzlogle** [comment] 2020-01-03 19:26
My other issues are less bugs and more enhancements that I haven't gotten around to logging yet. 
- support terraform.workspace in the schema
- support backend-config formats (in backend-config .tf's its just key = value)

**Closed** 2020-03-28 07:20 UTC
