### ISSUE TITLE
Update to 1.0.4 failing

### ISSUE THREAD

**Issue by cig0** [mauve/vscode-terraform#77] opened 2018-05-02 15:07 UTC
Hi,

I get this error message when updating the extension:
```
[Error - 12:05:19] (node:63252) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): [object Object]
[Error - 12:05:19] (node:63252) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 12:05:19] (node:63252) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): [object Object]
```
Thanks!

**Comment by mauve** [comment] 2018-05-02 17:31
I do not get any promise rejections when testing; are you sure they are because of this plugin? Please supply the stacktraces.

**Comment by cig0** [comment] 2018-05-02 17:32
Hi Mikael, thanks for your quick response. How do I get a stack trace of a VS Code extension?

**Comment by mauve** [comment] 2018-05-02 18:11
you might also be able to get the more information by just clicking `Help` > `Toggle Developer tools`

**Comment by mauve** [comment] 2018-05-03 15:45
I cannot reproduce this so closing now, feel free to reopen

**Closed by mauve** 2018-05-03 15:45 UTC

**Comment by cig0** [comment] 2018-05-17 14:32
Hi @mauve,
Indeed I haven't seen this issue again, I'm wondering if there was a kind of collision with other extension trying to update at the same time?
I'll let you know should I stumble into the error again.
Thanks!
